import = ["/home/andrew.fore/.config/alacritty/themes/catppuccin-mocha.toml"]

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[shell]
#args = ["-l", "-c", "zellij attach --index 0 || zellij"]
#program = "/bin/zsh"
program = "/usr/local/bin/nu"

[window]
#decorations = "none"
opacity = 0.85

[window.dimensions]
columns = 200
lines = 60

[window.position]
x = 80
y = 100
