import = ["~/Documents/Development/repos/alacritty-theme/themes/catppuccin_mocha.toml"]

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[shell]
# program = "/opt/homebrew/bin/nu"
program = "/opt/homebrew/bin/zsh"
args = ["-l"]

[window]
#decorations = "none"
opacity = 0.98
option_as_alt = "both"

[window.dimensions]
columns = 200
lines = 60

[window.position]
x = 80
y = 100

[[keyboard.bindings]]
key = "NumpadEnter"
chars = "\r"

[[hints.enabled]]
binding = { key = "U", mods = "Control|Shift" }
command = "xdg-open"
hyperlinks = true
mouse.enabled = true
mouse.mods = "Control"
post_processing = true
persist = false
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "T"
mods = "Command"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "N"
mods = "Command"
