format = """\
[](bg:#030B16 fg:#ff9e00)\
[ ](bg:#ff9e00 fg:#090c0c)\
[](fg:#ff9e00 bg:#1C3A5E)\
$time\
[](fg:#1C3A5E bg:#ff9e00)\
$directory\
[](fg:#ff9e00 bg:#1C3A5E)\
$git_branch\
$git_status\
$git_metrics\
[](fg:#1C3A5E bg:#ff9e00)\
$custom\
[](fg:#ff9e00 bg:#1C3A5E)\
$nodejs\
$aws\
[](fg:#1C3A5E bg:#00000)\
$character\
$cmd_duration\
"""
add_newline = false

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"~" = "  "

[directory]
format = "[$path ]($style)"
style = "bg:#ff9e00 fg:#090c0c"
truncation_length = 45
truncation_symbol = "  "

[git_branch]
format = '[ $symbol$branch(: $remote_branch )  ]($style)'
symbol = " "
style = "bg:#1C3A5E fg:#c1e3fe"

[git_status]
format = '[$all_status  ]($style)'
style = "bg:#1C3A5E fg:#c1e3fe"
conflicted = '[conflicted 󱚠](fg:#ff3334 bg:#1C3A5E)'
ahead = '[ahead  󰊍](bg:#1C3A5E fg:#E84D44)'
behind = '[behind   ](bg:#1C3A5E fg:#E84D44)'
diverged = '[diverged 󱡷 ](bg:#1C3A5E fg:#E84D44)'
up_to_date = '[upToDate ♥︎](bg:#1C3A5E fg:#7bff00)'
untracked = '[untracked  ](bg:#1C3A5E fg:#ff1e00)'
stashed = '[stashed 󱔘  ](bg:#1C3A5E fg:#7bff00)'
modified = '[mod 󰊳  ](bg:#1C3A5E fg:yellow)'
renamed = '[ren  ](bg:#1C3A5E fg:#E84D44)'
deleted = '[del 󱕖](fg:#ff3334 bg:#1C3A5E)'

[git_metrics]
format = "([+$added  ]($added_style))[]($added_style)([-$deleted  ]($deleted_style)[]($deleted_style))"
added_style = "bg:#1C3A5E fg:#7bff00"
deleted_style = "fg:#ff1e00 bg:#1C3A5E"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = ""

[cmd_duration]
min_time = 500
style = "bg:#ff1e00"
#format = '[](bg:#000000 fg:#1C3A5E)[ 󰔛 ](bg:#1C3A5E fg:#ffffff)($style)[$duration ](bg:#1C3A5E fg:#ff1e00)[](bg:#000000 fg:#1C3A5E)'
format = '[](bg:#000000 fg:#1C3A5E)[  ](bg:#1C3A5E fg:#ffffff)($style)[$duration ](bg:#1C3A5E fg:#ff1e00)[](bg:#000000 fg:#1C3A5E)'

[character]
#success_symbol = '[ λ](#7bff00) '
#error_symbol = '[ λ](#ff1e00) '
success_symbol = '[ ➜](#7bff00) '
error_symbol = '[ ➜](#7bff00) '

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](bg:#1C3A5E fg:#ffffff)]($style)'

[nodejs]
symbol = ""
format = '[[ $symbol ($version) ](bg:#1C3A5E fg:#c1e3fe)]($style)'
style = "bg:#1C3A5E fg:#c1e3fe"

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[terraform]
symbol = "󱁢"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#fffff bg:#fffff)]($style)'
detect_extensions = ['']
detect_files = ['']
detect_folders = ['']

[custom.tf]
command = 'tfenv version-name' # shows output of command
when = 'true'
format = '[[ $symbol ($output) ](bg:#ff9e00 fg:#090c0c)]($style)'
symbol = "󱁢"
style = "bg:#fffff fg:#fffff"

[aws]
format = '[ ☁️ AWS/$profile/($region) ]($style)'
style = 'fg:#ff9e00 bg:#1C3A5E'