"$schema" = "https://starship.rs/config-schema.json"

# colorscheme
#
# #2E3440
# #3B4252
# #434C5E
# #4C566A
# #D8DEE9
# #E5E9F0
# #ECEFF4
# #8FBCBB
# #88C0D0
# #81A1C1
# #5E81AC
# #BF616A
# #D08770
# #EBCB8B
# #A3BE8C
# #B48EAD

format = """
$username\
$directory\
$git_branch\
$git_status\
$golang\
$java\
$nodejs\
$rust\
$terraform\
$custom\
[\uE0B0 ](fg:#81A1C1 bg:#2E3440)\
$character
"""

[character]
#success_symbol = '[ λ](#7bff00) '
#error_symbol = '[ λ](#ff1e00) '
success_symbol = '[ ➜](#8FBCBB) '
error_symbol = '[ ➜](#A3BE8C) '

# system

[username]
show_always = true
style_user = "bg:#4C566A"
style_root = "bg:#4C566A"
format = "[ $user ]($style)[\uE0BC](bg:#BF616A fg:#4C566A)"

[directory]
style = "bg:#BF616A"
format = "[ $path ]($style)[\uE0BE](bg:#BF616A fg:#D08770)"
truncate_to_repo = false
truncation_length = 3
truncation_symbol = "…/"

# git

[git_branch]
format = '[ $symbol$branch(: $remote_branch )  ]($style)'
symbol = " "
style = "bg:#D08770"

[git_metrics]
disabled = false

[git_status]
format = "[($all_status$ahead_behind) ]($style)[\uE0BC](bg:#81A1C1 fg:#D08770)"
style = "bg:#D08770"
conflicted = "conflicted 󱚠 $count "
ahead = "ahead  󰊍 $count "
behind = "behind   $count "
diverged = "diverged 󱡷 $count "
untracked = "untracked  $count "
stashed = "stashed 󱔘 $count "
modified = "mod 󰊳 $count"
staged = "stg  $count "
renamed = "ren  $count "
deleted = "del 󱕖 $count "

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = ""

# languages

[c]
symbol = "© "
style = "bg:#D8DEE9"
format = "[[ $symbol ($version) ](bg:#D8DEE9)]($style)"

[elixir]
symbol = "\uE62D "
style = "bg:#D8DEE9"
format = "[[ $symbol ($version) ](bg:#D8DEE9)]($style)"

[elm]
symbol = "\uE62C "
style = "bg:#D8DEE9"
format = "[[ $symbol ($version) ](bg:#D8DEE9)]($style)"

[golang]
symbol = "\uE627 "
style = "bg:#81A1C1 fg:#4C566A"
format = "[ $symbol]($style)"

[haskell]
symbol = "\uE777 "
style = "bg:#D8DEE9"
format = "[[ $symbol($version)](bg:#D8DEE9)]($style)"

[nodejs]
symbol = "\uE718 "
style = "bg:#81A1C1 fg:#4C566A"
format = "[ $symbol]($style)"

[rust]
symbol = "\uE7A8 "
style = "bg:#D8DEE9"
format = "[[ $symbol($version) ](bg:#D8DEE9)]($style)"

[ruby]
symbol = "\uE739 "
style = "bg:#D8DEE9"
format = "[[ $symbol($version) ](bg:#D8DEE9)]($style)"

[terraform]
symbol = "󱁢"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#fffff bg:#fffff)]($style)'
detect_extensions = ['']
detect_files = ['']
detect_folders = ['']

[custom.tf]
command = 'tfenv version-name' # shows output of command
# when = 'true'
detect_extensions = ['tf']
format = '[[ $symbol ($output) ](bg:#8FBCBB fg:#090c0c)]($style)'
symbol = "󱁢"
style = "bg:#fffff fg:#fffff"

[aws]
format = '[ ☁️ AWS/$profile/($region) ]($style)'
style = 'fg:#ff9e00 bg:#1C3A5E'
